model:
  name: inceptionai/jais-family-6p7b-chat
  device: auto
  temperature: 0.3
  top_p: 0.9
  repetition_penalty: 1.2
  max_new_tokens: 20
  min_length_buffer: 4
  load_in_4bit: true

prompt:
  base: >
    ### Instruction:Your name is 'Jais', and you are named after Jebel Jais, the highest mountain in UAE. You were made by 'Inception' in the UAE. You are a helpful, respectful, and honest assistant. Always answer as helpfully as possible, while being safe. Complete the conversation between [|Human|] and [|AI|]:
    ### Input: [|Human|] {Question}
    [|AI|]
    ### Response :

task:
  sentiment: >
    ### Task
    Classify the following customer-service summary into **one** of: Positive, Neutral, or Negative.

    ### Labels
    - **Positive**: expressions of gratitude, praise, or clear problem resolution.
    - **Neutral**: strictly factual or informational statements with **no** emotional or evaluative content.
    - **Negative**: complaints, expressions of frustration, or unresolved issues.

    ### Examples
    1. Text: "I’m grateful for the quick support and resolution provided today."  
      Sentiment: Positive  
    2. Text: "I checked my account balance for today and noted the amount available."  
      Sentiment: Neutral  
    3. Text: "The agent confirmed my delivery date and provided a tracking number."  
      Sentiment: Neutral  
    4. Text: "I waited on hold for an hour and my issue remains unresolved."  
      Sentiment: Negative  
    5. Text: "The staff handled my request efficiently and ensured everything was updated."  
      Sentiment: Positive  

    ### Reasoning
    Please think step by step about whether this text contains **emotional content** or is **purely factual**, then answer with **only** the sentiment label.